;---BUILD-SCRIPT-FOR-AEROS-----------------------------------------------------------;
;---NAPALMTORCH:WINDOWS--------------------------------------------------------------;
;------------------------------------------------------------------------------------;

;---SET-VARIABLES--------------------------------------------------------------------;
setdir       C:/Users/Will/Documents/Github Projects/AerOS
setvar nasm  C:/GCC_7_1_0/bin/nasm.exe
setvar gcc   C:/GCC_7_1_0/bin/i686-elf-gcc.exe
setvar ld    C:/GCC_7_1_0/bin/i686-elf-ld.exe
setvar dbg   C:/GCC_7_1_0/bin/i686-elf-gdb.exe
setvar vm    C:\Program Files (x86)\VMware\VMware Workstation/vmrun.exe
setvar ramfs Tools/RAMFS/bin/Debug/net7.0/RAMFS.exe

;---CLEANUP-BIN-DIRECTORY------------------------------------------------------------;
rmdir Bin
mkdir Bin

;---ASSEMBLE-KERNEL-FILES------------------------------------------------------------;
recursive_io file_in.asm file_out.o Kernel/src Bin : nasm -felf32 #IN -o #OUT

;---COMPILE-KERNEL-FILES-------------------------------------------------------------;
recursive_io file_in.c file_out.o Kernel/src Bin : gcc -g -c #IN -o #OUT -IKernel/include -w -nostdlib -ffreestanding -Wall -Wextra -O2 -fno-rtti -fno-exceptions -fshort-enums -fsanitize=undefined -Werror=implicit-fallthrough -Werror=implicit-function-declaration -Werror=return-type

;---LINK-KERNEL-FILES----------------------------------------------------------------;
recursive .o Bin : ld -g -T Kernel/linker.ld -o Bin/kernel.elf #IN 

;---CREATE-RAMFS-IMAGE---------------------------------------------------------------;
ramfs Kernel/build_ramdisk.script

;---MAKE-ISO-IMAGE-------------------------------------------------------------------;
mkiso Tools/Limine Images/AerOS.iso Images/ISO Bin/kernel.elf Images/ramdisk.img

;---START-DEBUGGER-PIPE-AND-RUN-VMWARE-----------------------------------------------;
pipe AerOS
vm -T ws start Tools/VMWare/vmware_mach.vmx