#pragma once
#include <lib/types.h>
#include <lib/ctype.h>
#include <lib/stdio.h>
#include <lib/stdlib.h>
#include <lib/string.h>
#include <lib/kresult.h>
#include <core/multiboot.h>
#include <hal/vga.h>
#include <hal/serial.h>
